version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: form-builder-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - form-builder-network

  mongo-express:
    image: mongo-express:latest
    container_name: form-builder-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - form-builder-network

networks:
  form-builder-network:
    driver: bridge

volumes:
  mongodb_data: 